// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9g2iLCMp330fLzdNYLibUddvgwNKvstE',
    appId: '1:697096902235:web:d2d4bfcb91e8d2b32e917e',
    messagingSenderId: '697096902235',
    projectId: 'bdbancofapp',
    authDomain: 'bdbancofapp.firebaseapp.com',
    storageBucket: 'bdbancofapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qfEXsYwsEK0EQ0Zd_7D239hQk0wxO7A',
    appId: '1:697096902235:android:fb66940740b1aa102e917e',
    messagingSenderId: '697096902235',
    projectId: 'bdbancofapp',
    storageBucket: 'bdbancofapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMlAnepu253HIcvuslWDwTz7UwltuBQY',
    appId: '1:697096902235:ios:d31922a37a2903112e917e',
    messagingSenderId: '697096902235',
    projectId: 'bdbancofapp',
    storageBucket: 'bdbancofapp.firebasestorage.app',
    iosBundleId: 'com.example.bancofalabellaApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWMlAnepu253HIcvuslWDwTz7UwltuBQY',
    appId: '1:697096902235:ios:d31922a37a2903112e917e',
    messagingSenderId: '697096902235',
    projectId: 'bdbancofapp',
    storageBucket: 'bdbancofapp.firebasestorage.app',
    iosBundleId: 'com.example.bancofalabellaApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9g2iLCMp330fLzdNYLibUddvgwNKvstE',
    appId: '1:697096902235:web:60d36c56e740dcb82e917e',
    messagingSenderId: '697096902235',
    projectId: 'bdbancofapp',
    authDomain: 'bdbancofapp.firebaseapp.com',
    storageBucket: 'bdbancofapp.firebasestorage.app',
  );
}
